[DEFAULT]
expt_name = grid_rbf_pde_sdf

[EXPT]
n_coord_dims = 3
n_signal_dims = 1
target_type = sdf
loss_type = pde

[MODULE]
module_type = feature_grid
interpolation_type = rbf
feature_dim = 1
grid_resolution = 64
neighborhood_ring_size = 2
scales = 4
feature_decoder_type = linear

[TRAIN]
n_train_stratified_samples_per_dim = 64
n_train_data_samples_per_dim = 64
sampling_strategy = data_and_stratified
lrate = 1e-2
decay_lrate = False
lrate_decay_steps = 5000
lrate_decay_rate = 0.1
n_iterations = 20001

[TEST]
n_test_samples_per_dim = 128
i_test = 200

;point_cloud_path = assets/armadillo.ply
;point_cloud_path = assets/bun_zipper.ply