[DEFAULT]
expt_name = grid_rbf_pde_neuralclothsim

[EXPT]
n_coord_dims = 2
n_signal_dims = 3
target_type = neuralclothsim
loss_type = pde
boundary_condition = neuralclothsim_top_left_top_right_moved

[MODULE]
module_type = feature_grid
interpolation_type = rbf
feature_dim = 4
grid_resolution = 32
scales = 1
; Note: If using scales > 1, lower the lrate to 1e-3 for better convergence
feature_decoder_type = linear

[TRAIN]
n_train_stratified_samples_per_dim = 64
sampling_strategy = stratified
lrate = 1e-2
decay_lrate = False
lrate_decay_steps = 2000
lrate_decay_rate = 0.1
n_iterations = 2001

[TEST]
n_test_samples_per_dim = 64